# Generated by Django 3.1.5 on 2021-01-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('places', models.IntegerField(verbose_name='amount of places')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('year_of_production', models.IntegerField(verbose_name='year of production')),
                ('type', models.CharField(max_length=80)),
                ('duration_in_minutes', models.IntegerField(verbose_name='duration in minutes')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_day_numerical', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_hour', models.IntegerField()),
                ('start_minutes', models.IntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(check=models.Q(('year_of_production__gte', 1888), ('year_of_production__lt', 3000)), name='correct_year_of_production'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(check=models.Q(duration_in_minutes__gte=0), name='correct_duration_in_minutes'),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.CheckConstraint(check=models.Q(places__gte=0), name='correct_amount_of_places'),
        ),
        migrations.AddConstraint(
            model_name='showing',
            constraint=models.CheckConstraint(check=models.Q(('start_hour__gte', 0), ('start_hour__lte', 23)), name='correct_start_hour'),
        ),
        migrations.AddConstraint(
            model_name='showing',
            constraint=models.CheckConstraint(check=models.Q(('start_minutes__gte', 0), ('start_minutes__lte', 59)), name='correct_start_minutes'),
        ),
    ]
