# Generated by Django 3.1.5 on 2021-01-07 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_showing_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
