# Generated by Django 3.1.5 on 2021-01-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20210107_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showing',
            old_name='date',
            new_name='showing_date',
        ),
    ]
