# Generated by Django 3.1.5 on 2021-01-09 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_auto_20210109_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='start_minutes',
        ),
        migrations.AddField(
            model_name='showing',
            name='showing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
