# Generated by Django 3.1.5 on 2021-01-13 14:35

import cinema.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20210109_2037'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hall',
            name='correct_amount_of_places',
        ),
        migrations.RemoveConstraint(
            model_name='movie',
            name='correct_duration_in_minutes',
        ),
        migrations.AlterField(
            model_name='hall',
            name='places',
            field=models.IntegerField(validators=[cinema.validators.validate_correct_no_places], verbose_name='amount of places'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_in_minutes',
            field=models.IntegerField(validators=[cinema.validators.validate_correct_duration], verbose_name='duration in minutes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_of_production',
            field=models.IntegerField(validators=[cinema.validators.validate_correct_year_of_production], verbose_name='year of production'),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.CheckConstraint(check=models.Q(('places__gte', 0), ('places__lte', 400)), name='correct_amount_of_places'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(check=models.Q(('duration_in_minutes__gte', 0), ('duration_in_minutes__lte', 600)), name='correct_duration_in_minutes'),
        ),
    ]
