# Generated by Django 3.1.5 on 2021-01-08 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210108_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tickets_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
