# Generated by Django 3.1.5 on 2021-01-07 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='week_day_numerical',
        ),
        migrations.AddField(
            model_name='showing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='showing date'),
            preserve_default=False,
        ),
    ]
