# Generated by Django 3.1.5 on 2021-01-07 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20210107_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
