# Generated by Django 3.1.5 on 2021-01-08 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0007_auto_20210107_2317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('tickets_amount', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('cashier_who_accepted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_orders', to=settings.AUTH_USER_MODEL)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.showing')),
            ],
        ),
    ]
